In [1]:
import os
import cv2
import numpy as np
from sklearn import cluster
import matplotlib.pyplot as plt

In [2]:
path='./pictures/distance/'

In [3]:
images = []

for img in os.listdir(path):
    if os.path.isdir(path+img):
        # skip directories
        continue
    image = cv2.imread(path+img)
    # cv2.imshow('crop',image)
    # cv2.waitKey(0)
    images.append(image)

# cv2.destroyAllWindows()
len(images)

9

In [4]:
for img in os.listdir(f'{path}/query/'):
    query_img = cv2.imread(f'{path}/query/{img}')
    query_img = cv2.cvtColor(query_img, cv2.COLOR_BGR2HSV)
    cv2.imshow('q',query_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [5]:
hist_size=[8,4]

In [6]:
# query_img[:,:,2]=0
query_hist=cv2.calcHist([query_img],[0,1],None,hist_size,[0,180,0,256])
query_hist=query_hist.flatten()
query_hist /= query_hist.sum()

In [7]:
hhist=[]#np.zeros((len(images),8,4))

for i in range(len(images)):
    # print(i)
    img = np.copy(images[i])
    img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    # img[:,:,2]=0
    hist = cv2.calcHist([img],[0,1],None,hist_size,[0,180,0,256])
    hist /=hist.sum()
    # print(hist)
    # hhist[i]=np.array(hist, dtype=object)
    hhist.append(hist.flatten())

In [8]:
dd = []
for i in range(len(images)):
    d = cv2.compareHist(query_hist, hhist[i], cv2.HISTCMP_BHATTACHARYYA) 
    dd.append(d)

In [9]:
from scipy.spatial import distance
ee = []

#euclidean
for i in range(len(images)):
    e = distance.euclidean(query_hist, hhist[i])
    ee.append(e)


In [13]:
sdd=np.argsort(dd)

for i in sdd:
    print(f'{i} - {dd[i]}')
    cv2.imshow('q',images[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

6 - 0.5464692219050691
7 - 0.5895815683939126
8 - 0.7231856733090943
3 - 0.7956959031565003
4 - 0.8233643281640691
5 - 0.8242915767427949
2 - 0.8704685277756514
1 - 0.897695931445635
0 - 0.943462176146489


In [11]:
see=np.argsort(ee)

for i in see:
    print(f'{i} - {ee[i]}')

6 - 0.6113699674606323
8 - 0.6597704291343689
7 - 0.6844725012779236
2 - 0.7110666632652283
4 - 0.7665561437606812
3 - 0.7865217924118042
5 - 0.8222361207008362
0 - 0.9822821617126465
1 - 1.0481942892074585


In [12]:
# cv2.imshow('q',images[1])
# cv2.waitKey(0)
# cv2.destroyAllWindows()

QF

In [9]:
h = [22.5*t+11.25 for t in range(8)]
h

[11.25, 33.75, 56.25, 78.75, 101.25, 123.75, 146.25, 168.75]

In [11]:
s = [64*t+32 for t in range(4)]
s

[32, 96, 160, 224]

In [12]:
hh, ss = np.meshgrid(h, s)

In [14]:
hh, ss

(array([[ 11.25,  33.75,  56.25,  78.75, 101.25, 123.75, 146.25, 168.75],
        [ 11.25,  33.75,  56.25,  78.75, 101.25, 123.75, 146.25, 168.75],
        [ 11.25,  33.75,  56.25,  78.75, 101.25, 123.75, 146.25, 168.75],
        [ 11.25,  33.75,  56.25,  78.75, 101.25, 123.75, 146.25, 168.75]]),
 array([[ 32,  32,  32,  32,  32,  32,  32,  32],
        [ 96,  96,  96,  96,  96,  96,  96,  96],
        [160, 160, 160, 160, 160, 160, 160, 160],
        [224, 224, 224, 224, 224, 224, 224, 224]]))

In [15]:
A = np.zeros((32,32))

In [37]:
z = np.array([[i,j] for i,j in zip(hh.flatten(),ss.flatten())])
z

array([[ 11.25,  32.  ],
       [ 33.75,  32.  ],
       [ 56.25,  32.  ],
       [ 78.75,  32.  ],
       [101.25,  32.  ],
       [123.75,  32.  ],
       [146.25,  32.  ],
       [168.75,  32.  ],
       [ 11.25,  96.  ],
       [ 33.75,  96.  ],
       [ 56.25,  96.  ],
       [ 78.75,  96.  ],
       [101.25,  96.  ],
       [123.75,  96.  ],
       [146.25,  96.  ],
       [168.75,  96.  ],
       [ 11.25, 160.  ],
       [ 33.75, 160.  ],
       [ 56.25, 160.  ],
       [ 78.75, 160.  ],
       [101.25, 160.  ],
       [123.75, 160.  ],
       [146.25, 160.  ],
       [168.75, 160.  ],
       [ 11.25, 224.  ],
       [ 33.75, 224.  ],
       [ 56.25, 224.  ],
       [ 78.75, 224.  ],
       [101.25, 224.  ],
       [123.75, 224.  ],
       [146.25, 224.  ],
       [168.75, 224.  ]])

In [41]:
np.sqrt(((z[0]-z[1])**2).sum())

22.5

In [45]:
np.fromfunction(lambda i, j: np.sqrt(((z[i]-z[j])**2).sum()) , (3, 3), dtype=int)

77.94228634059948

In [44]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [55]:
from scipy.spatial import distance

A = distance.cdist(z, z, lambda i, j: 1-(np.sqrt(1/5)*np.sqrt((i[1]*np.cos(i[0])-j[1]*np.cos(j[0]))**2+(i[1]*np.sin(i[0])-j[1]*np.sin(j[0]))**2)))
A

array([[   1.        ,  -26.70028124,  -12.94374818, ...,  -87.70903282,
        -113.43768191,  -86.3064775 ],
       [ -26.70028124,    1.        ,  -26.70028124, ..., -106.35323317,
         -87.70903282, -113.43768191],
       [ -12.94374818,  -26.70028124,    1.        , ..., -100.81753009,
        -106.35323317,  -87.70903282],
       ...,
       [ -87.70903282, -106.35323317, -100.81753009, ...,    1.        ,
        -192.90196866,  -96.60623728],
       [-113.43768191,  -87.70903282, -106.35323317, ..., -192.90196866,
           1.        , -192.90196866],
       [ -86.3064775 , -113.43768191,  -87.70903282, ...,  -96.60623728,
        -192.90196866,    1.        ]])

In [62]:
v = np.dot((query_hist-hhist[1]),A)
w = np.dot(v,(query_hist-hhist[1]).T)
w

55.24306312135147

In [63]:
qd = []
for i in range(len(images)):
    v = np.dot((query_hist-hhist[i]),A)
    w = np.dot(v,(query_hist-hhist[i]).T)
    qd.append(w)

In [64]:
sqf=np.argsort(qd)

for i in sqf:
    print(f'{i} - {qd[i]}')

2 - 31.29600130819564
6 - 38.740419840032814
3 - 44.78380080596953
4 - 46.122812749521174
5 - 47.58567431853193
0 - 53.98481756289907
8 - 54.51593086320051
1 - 55.24306312135147
7 - 56.07306324189969


In [66]:
cv2.imshow('q',images[2])
cv2.waitKey(0)
cv2.destroyAllWindows()